[package]
name = "enum_rotate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_enum_rotate = { path = "../derive_enum_rotate" }
delegate = "0.12.0"
