[package]
name = "enum_rotate"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_enum_rotate = { path = "../derive_enum_rotate" }

[dev-dependencies]
paste = "1.0.14"
#compiletest_rs = { version = "0.10.2", features = [ "rustc" ] }
